development:
  adapter: mysql2
  database: the_milky_way_db
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  encoding: utf8
  pool: 5

test:
  adapter: mysql2
  database: testdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  encoding: utf8
  pool: 5

production:
  adapter: mysql2
  database: Railsdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  encoding: utf8
  pool: 5
